// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prueba_Tecnica.Models;

#nullable disable

namespace Prueba_Tecnica.Migrations
{
    [DbContext(typeof(FondoXyzContext))]
    [Migration("20250518041331_Imagenes")]
    partial class Imagenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prueba_Tecnica.Models.Alojamiento", b =>
                {
                    b.Property<int>("IdAlojamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlojamiento"));

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<bool?>("Cocina")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cocineta")
                        .HasColumnType("bit");

                    b.Property<bool?>("Comedor")
                        .HasColumnType("bit");

                    b.Property<int?>("IdSede")
                        .HasColumnType("int");

                    b.Property<bool?>("Nevera")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumeroBanos")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroHabitaciones")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("Sala")
                        .HasColumnType("bit");

                    b.Property<bool?>("SofaCama")
                        .HasColumnType("bit");

                    b.Property<bool?>("Televisor")
                        .HasColumnType("bit");

                    b.Property<bool?>("Terraza")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAlojamiento")
                        .HasName("PK__Alojamie__EF77F57275F8EE02");

                    b.HasIndex("IdSede");

                    b.ToTable("Alojamiento", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.AlojamientosCapacidadTotal", b =>
                {
                    b.Property<int>("IdAlojamientosCapacidadTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlojamientosCapacidadTotal"));

                    b.Property<int?>("CapacidadTotal")
                        .HasColumnType("int");

                    b.Property<int?>("IdSede")
                        .HasColumnType("int");

                    b.HasKey("IdAlojamientosCapacidadTotal")
                        .HasName("PK__Alojamie__6827F5EDB2C1EC28");

                    b.ToTable("AlojamientosCapacidadTotal", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Apartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadHabitaciones")
                        .HasColumnType("int");

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<bool>("EsHabitacion")
                        .HasColumnType("bit");

                    b.Property<int?>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TieneCocina")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneParqueadero")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneSalaComedor")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Apartame__3214EC07B3C5E9FD");

                    b.HasIndex("IdCiudad");

                    b.ToTable("Apartamento", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoBano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdApartamento")
                        .HasColumnType("int");

                    b.Property<bool?>("TieneBanoPrivado")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Apartame__3214EC07A1AF1EDA");

                    b.HasIndex("IdApartamento");

                    b.ToTable("ApartamentoBanos");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoCama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdApartamento")
                        .HasColumnType("int");

                    b.Property<string>("TipoCama")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Apartame__3214EC07064A1CB5");

                    b.HasIndex("IdApartamento");

                    b.ToTable("ApartamentoCamas");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoCiudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Apartame__3214EC073BE357A5");

                    b.ToTable("ApartamentoCiudad", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Cama", b =>
                {
                    b.Property<int>("IdCama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCama"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCama")
                        .HasName("PK__Cama__3B7B1B619E80F075");

                    b.HasIndex("IdHabitacion");

                    b.ToTable("Cama", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<int?>("IdAlojamiento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdHabitacion")
                        .HasName("PK__Habitaci__8BBBF901B69ECC42");

                    b.HasIndex("IdAlojamiento");

                    b.ToTable("Habitacion", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Sede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSede"));

                    b.Property<int?>("CapacidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSede")
                        .HasName("PK__Sede__A7780DFF310ACB83");

                    b.ToTable("Sede", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ServicioSede", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<int?>("IdSede")
                        .HasColumnType("int");

                    b.Property<string>("Servicio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdServicio")
                        .HasName("PK__Servicio__2DCCF9A29A0CCA8E");

                    b.HasIndex("IdSede");

                    b.ToTable("ServicioSede", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaAlojamiento", b =>
                {
                    b.Property<int>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifa"));

                    b.Property<int?>("IdAlojamiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdTemporada")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroHabitacion")
                        .HasColumnType("int");

                    b.Property<int?>("PersonasIncluidas")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("IdTarifa")
                        .HasName("PK__TarifaAl__78F1A91D42C6EF78");

                    b.HasIndex("IdAlojamiento");

                    b.HasIndex("IdTemporada");

                    b.ToTable("TarifaAlojamiento", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaApartamento", b =>
                {
                    b.Property<int>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifa"));

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("IdTemporada")
                        .HasColumnType("int");

                    b.Property<int?>("PersonasIncluidas")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("IdTarifa")
                        .HasName("PK__TarifaAp__78F1A91DA8173760");

                    b.HasIndex("Id");

                    b.HasIndex("IdTemporada");

                    b.ToTable("TarifaApartamento", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaLavanderium", b =>
                {
                    b.Property<int>("IdTarifaLavanderia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifaLavanderia"));

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("IdTarifaLavanderia")
                        .HasName("PK__TarifaLa__0924F76CBAC003F7");

                    b.ToTable("TarifaLavanderia");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaPersonaAdicional", b =>
                {
                    b.Property<int>("IdTarifaPersonaAdicional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifaPersonaAdicional"));

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("IdTarifaPersonaAdicional")
                        .HasName("PK__TarifaPe__8C301A86B84D09F3");

                    b.ToTable("TarifaPersonaAdicional", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaPersonaAdicionalTemporadum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdTarifaPersonaAdicional")
                        .HasColumnType("int");

                    b.Property<int?>("IdTemporada")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("Id")
                        .HasName("PK__TarifaPe__3214EC0727863DBC");

                    b.HasIndex("IdTarifaPersonaAdicional");

                    b.HasIndex("IdTemporada");

                    b.ToTable("TarifaPersonaAdicional_Temporada", (string)null);
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaVisitaDium", b =>
                {
                    b.Property<int>("IdTarifaVisitaDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarifaVisitaDia"));

                    b.Property<int?>("MaximoPersonas")
                        .HasColumnType("int");

                    b.Property<int?>("MinimoPersonas")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("money");

                    b.HasKey("IdTarifaVisitaDia")
                        .HasName("PK__TarifaVi__1F619C9F90B3051B");

                    b.ToTable("TarifaVisitaDia");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Temporadum", b =>
                {
                    b.Property<int>("IdTemporada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTemporada"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTemporada")
                        .HasName("PK__Temporad__80F418213553B873");

                    b.ToTable("Temporada");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Alojamiento", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Sede", "IdSedeNavigation")
                        .WithMany("Alojamientos")
                        .HasForeignKey("IdSede")
                        .HasConstraintName("FK__Alojamien__IdSed__5629CD9C");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Apartamento", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.ApartamentoCiudad", "IdCiudadNavigation")
                        .WithMany("Apartamentos")
                        .HasForeignKey("IdCiudad")
                        .HasConstraintName("FK__Apartamen__IdCiu__4BAC3F29");

                    b.Navigation("IdCiudadNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoBano", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Apartamento", "IdApartamentoNavigation")
                        .WithMany("ApartamentoBanos")
                        .HasForeignKey("IdApartamento")
                        .HasConstraintName("FK__Apartamen__IdApa__5165187F");

                    b.Navigation("IdApartamentoNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoCama", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Apartamento", "IdApartamentoNavigation")
                        .WithMany("ApartamentoCamas")
                        .HasForeignKey("IdApartamento")
                        .HasConstraintName("FK__Apartamen__IdApa__4E88ABD4");

                    b.Navigation("IdApartamentoNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Cama", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Habitacion", "IdHabitacionNavigation")
                        .WithMany("Camas")
                        .HasForeignKey("IdHabitacion")
                        .HasConstraintName("FK__Cama__IdHabitaci__5DCAEF64");

                    b.Navigation("IdHabitacionNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Habitacion", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Alojamiento", "IdAlojamientoNavigation")
                        .WithMany("Habitacions")
                        .HasForeignKey("IdAlojamiento")
                        .HasConstraintName("FK__Habitacio__IdAlo__5AEE82B9");

                    b.Navigation("IdAlojamientoNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ServicioSede", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Sede", "IdSedeNavigation")
                        .WithMany("ServicioSedes")
                        .HasForeignKey("IdSede")
                        .HasConstraintName("FK__ServicioS__IdSed__60A75C0F");

                    b.Navigation("IdSedeNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaAlojamiento", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Alojamiento", "IdAlojamientoNavigation")
                        .WithMany("TarifaAlojamientos")
                        .HasForeignKey("IdAlojamiento")
                        .HasConstraintName("FK__TarifaAlo__IdAlo__693CA210");

                    b.HasOne("Prueba_Tecnica.Models.Temporadum", "IdTemporadaNavigation")
                        .WithMany("TarifaAlojamientos")
                        .HasForeignKey("IdTemporada")
                        .HasConstraintName("FK__TarifaAlo__IdTem__6A30C649");

                    b.Navigation("IdAlojamientoNavigation");

                    b.Navigation("IdTemporadaNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaApartamento", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.Apartamento", "IdNavigation")
                        .WithMany("TarifaApartamentos")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK__TarifaAparta__Id__656C112C");

                    b.HasOne("Prueba_Tecnica.Models.Temporadum", "IdTemporadaNavigation")
                        .WithMany("TarifaApartamentos")
                        .HasForeignKey("IdTemporada")
                        .HasConstraintName("FK__TarifaApa__IdTem__66603565");

                    b.Navigation("IdNavigation");

                    b.Navigation("IdTemporadaNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaPersonaAdicionalTemporadum", b =>
                {
                    b.HasOne("Prueba_Tecnica.Models.TarifaPersonaAdicional", "IdTarifaPersonaAdicionalNavigation")
                        .WithMany("TarifaPersonaAdicionalTemporada")
                        .HasForeignKey("IdTarifaPersonaAdicional")
                        .HasConstraintName("FK__TarifaPer__IdTar__70DDC3D8");

                    b.HasOne("Prueba_Tecnica.Models.Temporadum", "IdTemporadaNavigation")
                        .WithMany("TarifaPersonaAdicionalTemporada")
                        .HasForeignKey("IdTemporada")
                        .HasConstraintName("FK__TarifaPer__IdTem__71D1E811");

                    b.Navigation("IdTarifaPersonaAdicionalNavigation");

                    b.Navigation("IdTemporadaNavigation");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Alojamiento", b =>
                {
                    b.Navigation("Habitacions");

                    b.Navigation("TarifaAlojamientos");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Apartamento", b =>
                {
                    b.Navigation("ApartamentoBanos");

                    b.Navigation("ApartamentoCamas");

                    b.Navigation("TarifaApartamentos");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.ApartamentoCiudad", b =>
                {
                    b.Navigation("Apartamentos");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Habitacion", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Sede", b =>
                {
                    b.Navigation("Alojamientos");

                    b.Navigation("ServicioSedes");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.TarifaPersonaAdicional", b =>
                {
                    b.Navigation("TarifaPersonaAdicionalTemporada");
                });

            modelBuilder.Entity("Prueba_Tecnica.Models.Temporadum", b =>
                {
                    b.Navigation("TarifaAlojamientos");

                    b.Navigation("TarifaApartamentos");

                    b.Navigation("TarifaPersonaAdicionalTemporada");
                });
#pragma warning restore 612, 618
        }
    }
}
